[package]
edition = "2018"
name = "ra_cli"
version = "0.1.0"
authors = ["rust-analyzer developers"]
publish = false

[dependencies]
pico-args = "0.3.0"
env_logger = { version = "0.7.1", default-features = false, features = ["humantime"] }

ra_syntax = { path = "../ra_syntax" }
ra_ide = { path = "../ra_ide" }
ra_batch = { path = "../ra_batch" }
ra_hir = { path = "../ra_hir" }
ra_db = { path = "../ra_db" }

[dependencies.ra_prof]
path = "../ra_prof"
# features = [ "cpu_profiler" ]
# features = [ "jemalloc" ]
